### ISSUE TITLE
Microsoft .NET Framework Issue

### ISSUE THREAD

**Issue by ChrisK0007** [stackTom/FSEarthTiles#20]
Hello,

I'm having a issue with FSTiles coming up with a Microsoft .NET Framework error and then crashing shorlty after.

Help would be much appreciated. 

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Exception: Unknown way relation
   at AutomaticWaterMasking.WaterMasking.DrawInlandPolys(List`1 polys, Bitmap bmp, Graphics g, Point NW, Decimal pixelsPerLon, Decimal pixelsPerLat)
   at AutomaticWaterMasking.WaterMasking.GetMask(Dictionary`2 allMaskingPolys, Int32 pixelsX, Int32 pixelsY, Point NW, Decimal pixelsPerLon, Decimal pixelsPerLat, Graphics g, Bitmap bmp)
   at FSEarthTilesDLL.FSEarthTilesForm.AreaAllWater() in G:\FSEarthTiles\FSEarthTiles\FSEarthTilesDLL\FSEarthTilesForm.cs:line 9542
   at FSEarthTilesDLL.FSEarthTilesForm.MainThreadTimerEventProcessor(Object myObject, EventArgs myEventArgs) in G:\FSEarthTiles\FSEarthTiles\FSEarthTilesDLL\FSEarthTilesForm.cs:line 7651
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by stackTom** [comment]
Hi, can you send me your partialfsearthtiles.ini so I can investigate? To get this, go to the area you're trying to create and press the E button. It should create the file in your working directory. Thanks

**Comment by stackTom** [comment]
Go to your working folder. Then Tiles\+36+127. Delete every file inside Tiles\+36+127.
There was an error in the openstreetmap data. I have fixed this bad data on openstreetmap, and now it works fine.

**Comment by ChrisK0007** [comment]
Thank you, that fixed that area.
This area is also having the same issue: https://1drv.ms/u/s!AuUPIupEkMfjgrMb8wZkNMbJdBABog?e=g4yfLC

**Comment by stackTom** [comment]
Now, delete everything inside the +31+119 folder, and try again. OSM had bad data here as well which I've just fixed.

**Comment by ChrisK0007** [comment]
Many thanks!

**Comment by stackTom** [comment]
No problem, let me know any other issues.
