### ISSUE TITLE
Issue with FSET - what that might be ?

### ISSUE THREAD

**Issue by Artpom** [stackTom/FSEarthTiles#32]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at ASToFra.scenProc.Steps.Arguments.Filter.FillAttributes()
   at ASToFra.scenProc.Steps.Arguments.Filter.OnTriggerConfigurationReload(ConfigurationChange change)
   at ASToFra.Interfaces.TriggerConfigurationReload.Invoke(ConfigurationChange change)
   at ASToFra.Interfaces.EventDistributor.RaiseTriggerConfigurationReload(ConfigurationChange change)
   at ASToFra.scenProc.MainWindow.RaiseTriggerConfigurationReload(ConfigurationChange change)
   at ASToFra.scenProc.MainWindow.bwScan_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9277.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
scenProc
    Assembly Version: 1.0.0.0
    Win32 Version: 3.0.0.0
    CodeBase: file:///F:/FSET/scenProc_3.0_x64/scenProc.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9251.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9261.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
ASToFra.Utils
    Assembly Version: 1.0.0.0
    Win32 Version: 1.5.0.0
    CodeBase: file:///F:/FSET/scenProc_3.0_x64/ASToFra.Utils.DLL
----------------------------------------
ASToFra.Interfaces
    Assembly Version: 1.0.0.0
    Win32 Version: 1.5.0.0
    CodeBase: file:///F:/FSET/scenProc_3.0_x64/ASToFra.Interfaces.DLL
----------------------------------------
ASToFra.ErrorHandler
    Assembly Version: 1.0.0.0
    Win32 Version: 1.5.0.0
    CodeBase: file:///F:/FSET/scenProc_3.0_x64/ASToFra.ErrorHandler.DLL
----------------------------------------
ASToFra.scenProc.DataModel
    Assembly Version: 1.0.0.0
    Win32 Version: 3.0.0.0
    CodeBase: file:///F:/FSET/scenProc_3.0_x64/ASToFra.scenProc.DataModel.DLL
----------------------------------------
ASToFra.scenProc.Processor
    Assembly Version: 1.0.0.0
    Win32 Version: 3.0.0.0
    CodeBase: file:///F:/FSET/scenProc_3.0_x64/ASToFra.scenProc.Processor.DLL
----------------------------------------
DigitalRune.Windows.TextEditor
    Assembly Version: 1.3.0.0
    Win32 Version: 1.3.0.0
    CodeBase: file:///F:/FSET/scenProc_3.0_x64/DigitalRune.Windows.TextEditor.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9277.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
ASToFra.EventLog
    Assembly Version: 1.0.0.0
    Win32 Version: 1.5.0.0
    CodeBase: file:///F:/FSET/scenProc_3.0_x64/ASToFra.EventLog.DLL
----------------------------------------
ASToFra.LicenseHelper
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///F:/FSET/scenProc_3.0_x64/ASToFra.LicenseHelper.DLL
----------------------------------------
Portable.Licensing
    Assembly Version: 1.0.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///F:/FSET/scenProc_3.0_x64/Portable.Licensing.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
gdal_csharp
    Assembly Version: 1.0.6962.42234
    Win32 Version: 1.0.6962.42234
    CodeBase: file:///F:/FSET/scenProc_3.0_x64/gdal_csharp.DLL
----------------------------------------
ogr_csharp
    Assembly Version: 1.0.6962.42232
    Win32 Version: 1.0.6962.42232
    CodeBase: file:///F:/FSET/scenProc_3.0_x64/ogr_csharp.DLL
----------------------------------------
ASToFra.FSUtils
    Assembly Version: 1.0.0.0
    Win32 Version: 1.5.0.0
    CodeBase: file:///F:/FSET/scenProc_3.0_x64/ASToFra.FSUtils.DLL
----------------------------------------
AF2Utils
    Assembly Version: 1.0.8018.38920
    Win32 Version: 1.0.8018.38920
    CodeBase: file:///F:/FSET/scenProc_3.0_x64/AF2Utils.DLL
----------------------------------------
ASToFra.ObjectWriter
    Assembly Version: 1.0.0.0
    Win32 Version: 1.5.0.0
    CodeBase: file:///F:/FSET/scenProc_3.0_x64/ASToFra.ObjectWriter.DLL
----------------------------------------
System.DirectoryServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.DirectoryServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.DirectoryServices.dll
----------------------------------------
ASToFra.scenProc.Steps
    Assembly Version: 1.0.0.0
    Win32 Version: 3.0.0.0
    CodeBase: file:///F:/FSET/scenProc_3.0_x64/ASToFra.scenProc.Steps.DLL
----------------------------------------
ASToFra.ObjectModel3D
    Assembly Version: 1.0.0.0
    Win32 Version: 1.5.0.0
    CodeBase: file:///F:/FSET/scenProc_3.0_x64/ASToFra.ObjectModel3D.DLL
----------------------------------------
ASToFra.AutogenConfiguration
    Assembly Version: 1.0.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///F:/FSET/scenProc_3.0_x64/ASToFra.AutogenConfiguration.DLL
----------------------------------------
FlightToolkit.SimProp
    Assembly Version: 1.0.5.0
    Win32 Version: 1.0.5.0
    CodeBase: file:///F:/FSET/scenProc_3.0_x64/FlightToolkit.SimProp.DLL
----------------------------------------
Microsoft.WindowsAPICodePack.Shell
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///F:/FSET/scenProc_3.0_x64/Microsoft.WindowsAPICodePack.Shell.DLL
----------------------------------------
Microsoft.WindowsAPICodePack
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///F:/FSET/scenProc_3.0_x64/Microsoft.WindowsAPICodePack.DLL
----------------------------------------
Ciloci.Flee
    Assembly Version: 0.9.26.0
    Win32 Version: 0.9.26.0
    CodeBase: file:///F:/FSET/scenProc_3.0_x64/Ciloci.Flee.DLL
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.8.9037.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
ASToFra.Geometry
    Assembly Version: 1.0.0.0
    Win32 Version: 1.5.0.0
    CodeBase: file:///F:/FSET/scenProc_3.0_x64/ASToFra.Geometry.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by stackTom** [comment]
Seems to be a crash with scenproc. What version of scenproc are you using? Also, please send me the partialfsearthtiles.ini so I can reproduce it.

**Comment by Artpom** [comment]
scenProc 3.0_x64
where to find partialfsearthtiles.ini ?

**Comment by stackTom** [comment]
Press the E button on the top right of the program. It will create that file inside of your specified work folder.

Did you download scenproc recently?

**Comment by Artpom** [comment]
#--- Partial FS Earth Tiles ini datas ---

[FSEarthTiles]

AreaDefinitionMode       = 2Points
NorthWestCornerLatitude  = 26deg 25min 17.97sec north
NorthWestCornerLongitude = 80deg 51min 33.44sec west
SouthEastLatitude        = 26deg 24min 42.03sec north
SouthEastLongitude       = 80deg 50min 26.56sec west

Yes, i got scenproc quite recently from there https://www.scenerydesign.org/scenproc/

**Comment by stackTom** [comment]
I will try it, but that looks like a bug with scenproc. Anyway you can download an older version of scenproc?

**Comment by Artpom** [comment]
On given web page i see only latest version, from where i can download older version, and which one is stable ?

**Comment by stackTom** [comment]
Haven't had time to try to reproduce your bug. However, you can find older versions here:

https://www.fsdeveloper.com/forum/resources/scenproc-x64-stable-release.250/history

I haven't used scenproc in a while, but I believe version 2.0 is the last I used that works well. Make sure to run scenproc manually at least once before running it with FSET. Let me know if 2.0 or another old version eliminates your error.

**Comment by Artpom** [comment]
2.0 works ok but it is slow, 3.1 is much better and also more stable than 3.0

**Comment by stackTom** [comment]
Might want to contact Arno on fsdeveloper. I'll try to see if it's an issue with fset. But based on the error message, I think it's a bug with the newer version of scenproc.
